version: "3"

services:
  # app:
  #   build:
  #     context: .
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - organization
  #   depends_on: 
  #     - pg
  pg:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    networks:
      - organization
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aslpm
      POSTGRES_USER: amit
      POSTGRES_PASSWORD: 12345
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - organization
  celery_beat:
    build:
      context: .
    command: celery -A celery_config:celery_app beat
    networks:
      - organization
    depends_on:
      # - app
      - pg
      - redis
  
  celery_worker:
    build:
      context: .
    command: celery -A celery_config:celery_app worker --loglevel=info
    networks:
      - organization
    depends_on:
      # - app
      - pg
      - redis
  
    
volumes:
  postgres_data:

networks:
  organization:
    driver: bridge
