name: Pytest with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yaml up -d
        working-directory: .

      - name: Wait for services to start
        run: docker-compose -f docker-compose.yaml ps
        working-directory: .

      - name: Run Pytest
        run: docker-compose -f docker-compose.yaml exec pytest | cat
        working-directory: .
